version: '3'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/init.docker.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "2349:5432"
