version: '3'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/init.docker.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "2349:5432"
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "reward_service", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5
  reward_service:
    image: gamezop/interview-assignment:sc-rewards-0.0.2
    network_mode: host
    restart: unless-stopped
    ports:
      - "3010:3010"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLAGS_ONLY_SUCCESSFULLY_ORDERS=false
      - DB_REWARD_PAYOUTS_URI=postgres://postgres:postgres@localhost:2349/reward_service?sslmode=disable