// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repo

import (
	"fmt"

	"github.com/google/uuid"
)

type OrderStatus string

const (
	OrderStatusPending OrderStatus = "pending"
	OrderStatusSuccess OrderStatus = "success"
	OrderStatusFailed  OrderStatus = "failed"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type RewardPayout struct {
	ID      int64
	OrderID uuid.UUID
	Status  OrderStatus
	ScID    uuid.UUID
}
