name: ci
on:
  push:

jobs:
  test:
    uses: gamezop/github-action-workflows/.github/workflows/golang-test.yaml@main
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GO_MODULES_GITHUB_TOKEN }}
    with:
      go_version: 1.17
      run_docker_login: false
      test_docker_compose_path: ./docker-compose-test-ci.yaml
