name: ci
on:
  push:

jobs:
  test:
    uses: gamezop/github-action-workflows/.github/workflows/golang-test.yaml@master
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GO_MODULES_GITHUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    with:
      go_version: 1.17
      run_static_check: false
      test_docker_compose_path: ./docker-compose-test-ci.yaml
